version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/srv

  php:
    build: ./docker/php
    volumes:
      - .:/srv

  mariadb:
    image: mariadb:latest
    volumes: 
      - .:/srv
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db